export const newsSections = [
    {id: '0', 
    text:'Tungro Padi', 
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Rice_plants_affected_by_tungro_disease1.jpg/640px-Rice_plants_affected_by_tungro_disease1.jpg',
    contentTitle:'Pengendalian Penyakit:',
    content_1:'1) Penyemprotan insektisida',
    content_2:'2) Sanitasi lingkungan',
    content_3:'3) Melakukan tanam serempak',
    content_4:'4) Pengolahan tanah secara baik',
    content_5:'5) Pengaturan waktu tanam terhadap fluktuasi wereng hijau'},
    {id: '1',
     text:'Blas Padi', 
     image:'https://medialampung.co.id/wp-content/uploads/2020/09/blas.jpg',
     contentTitle:'Pengendalian Penyakit:',
     content_1:'1) Pengendalian dengan varietas tahan secara bergantian',
     content_2:'2) Jarak tanam tidak terlalu rapat',
     content_3:'3) Penanaman dengan benih sehat',
     content_4:'4) Penggunaan pupuk nitrogen dan kalium',
     content_5:'5) Penggunaan fungisida dengan bahan aktif metil tiofanat, fosdifen, kaugamisin'},
    {id: '2', 
    text:'Bercak Coklat Daun', 
    image:'https://krishijagran.com/media/42176/pest.png',
    contentTitle:'Pengendalian Penyakit:',
    content_1:'1) Meningkatkan kesuburan tanah dengan manajemen pupuk yang baik',
    content_2:'2) Pengelolaan air yang tepat',
    content_3:'3) Merenggangkan jarak tanam',
    content_4:'4) Mencelupkan benih pada larutan merkuri',
    content_5:'5) Melakukan rotasi tanaman untuk mengurangi intensitas penyebaran penyakit'},
    {id: '3', 
    text:'Hawar Daun', 
    image:'http://www.knowledgebank.irri.org/images/stories/bacterial-leaf-blight-1.JPG',
    contentTitle:'Pengendalian Penyakit:',
    content_1:'1) Melakukan sanitasi pada tanaman inang',
    content_2:'2) Sanitasi pada rerumputan sumber pathogen',
    content_3:'3) Menghindari pemupukan ketika tanaman memasuki fase bunting',
    content_4:'4) Melakukan pengairan berselang yaitu 1 hari dialiri dan 3-4 hari dikeringkan',
    content_5:'5) Menghindari penggenangan yang terlalu dalam'}  
]